plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mobilemorph.agent'
    compileSdk 33
    //buildToolsVersion "33.0.2"

    defaultConfig {
        applicationId "com.mobilemorph.agent"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            outputFileName = "mmagent-${variant.name}.apk"
        }
    }

    configurations.all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.10"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10"
        }
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation "androidx.work:work-runtime:2.8.1"
    implementation "androidx.annotation:annotation:1.7.1"
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
    implementation ('io.socket:socket.io-client:2.0.1') {
        exclude group: 'org.json', module: 'json'
    }
    implementation "androidx.core:core:1.10.1"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
}
