plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mobilemorph.agent'
    compileSdk 33
    //buildToolsVersion "33.0.2"

    defaultConfig {
        applicationId "com.mobilemorph.agent"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            storeFile       file("$rootDir/keystore/mmagent.jks")
            storePassword   System.getenv("KEYSTORE_PASS")
            keyAlias        "mmagent"
            keyPassword     System.getenv("KEY_PASS")
            enableV1Signing false       // turn off Janus-prone v1
            enableV2Signing true
            enableV3Signing true        
            enableV4Signing true        
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            debuggable false        // overrides any manifest value
            manifestPlaceholders = [appDebuggable:"false"]
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            outputFileName = "mmagent-${variant.name}.apk"
        }
    }

    configurations.all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.10"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10"
        }
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation "androidx.work:work-runtime:2.10.3"
    implementation "androidx.annotation:annotation:1.9.1"
    implementation 'androidx.security:security-crypto:1.1.0'
    implementation ('io.socket:socket.io-client:2.1.2') {
        exclude group: 'org.json', module: 'json'
    }
    implementation "androidx.core:core:1.17.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
    implementation ("co.elastic.apm:elastic-otel-android:1.15.0")
}
